dist: xenial
services: docker
language: bash
addons:
    apt:
        config:
            retries: true
        update: true
        sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu bionic main universe'
        packages:
            # Install wget >= 1.19.1 to use wget --retry-on-http-error=NNN,NNN option
            # https://lists.gnu.org/archive/html/bug-wget/2017-02/msg00065.html
            # https://packages.ubuntu.com/bionic/wget
            - wget
env:
    matrix:
        - ARCHS=alpha
        - ARCHS=amd64
        - ARCHS=arm64
        - ARCHS=armel
        - ARCHS=armhf
        - ARCHS=hppa
        - ARCHS=hurd-i386
        - ARCHS=i386
        - ARCHS=kfreebsd-amd64
        - ARCHS=kfreebsd-i386
        - ARCHS=m68k
        - ARCHS=mips
        - ARCHS=mipsel
        - ARCHS=powerpc
        - ARCHS=powerpcspe
        - ARCHS=ppc64
        - ARCHS=ppc64el
        - ARCHS=s390x
        - ARCHS=sh4
        - ARCHS=sparc64
        - ARCHS=x32
before_install:
    - docker run --rm --privileged multiarch/qemu-user-static:register
script:
    - ./update.sh
    - docker images
